nAnswer = input('Write your name: ')
aAnswer = input('Write your age: ')
print(' Me: Hello!, what is your name?')
print('User: Hie! My name is', nAnswer)
print('Me: Nice to meet you! I am Din, mind to tell me your age?')
print('User: Nice to meet you too! I am', aAnswer, 'years old')
